name: Build, Push, and Deploy Docker Image to EC2

on:
  push:
    branches:
      - main  # Or your preferred branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp:image001 .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/myapp:image001

    - name: Set up SSH key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
        chmod 600 private_key.pem

    - name: Add EC2 host to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts

    - name: SSH to EC2 and deploy container
      run: |
        ssh -i private_key.pem ec2-user@${{ secrets.EC2_IP }} << 'EOF'
          docker pull ${{ secrets.DOCKER_USERNAME }}/myapp:image001
          docker stop myapp || true
          docker rm myapp || true
          docker run -d -p 80:3000 --name myapp ${{ secrets.DOCKER_USERNAME }}/myapp:image001
        EOF
