name: Deploy Docker Image to EC2

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: SSH to EC2 and pull Docker image, stop old container, and run new container
        run: |
          ssh -i private_key.pem ec2-user@${{ secrets.EC2_IP }} << 'EOF'
            # Pull the latest image from Docker Hub
            docker pull jaykisen/your-image-name:image001

            # Stop and remove any old container
            docker stop myapp || true
            docker rm myapp || true

            # Run the new container
            docker run -d -p 3000:3000 --name myapp jaykisen/your-image-name:image001
          EOF
